server:
  port: ${SERVER_PORT:8445}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: mypass
    key-store-type: PKCS12

REDIRECT_URI: https://localhost:8445/index.html
APP_ID: 400280877270003
APP_SECRET: f91e94a81602def0e8a5d627699bf898